# Generated by Django 5.2.10 on 2026-01-15 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specimen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specimen_id', models.CharField(max_length=100, unique=True, verbose_name='Specimen ID')),
                ('collection_id', models.CharField(blank=True, max_length=100, verbose_name='Collection ID')),
                ('type', models.CharField(choices=[('BLOOD', 'Blood'), ('SERUM', 'Serum'), ('PLASMA', 'Plasma'), ('DNA', 'DNA'), ('RNA', 'RNA'), ('TISSUE', 'Tissue'), ('URINE', 'Urine'), ('OTHER', 'Other')], default='OTHER', max_length=20, verbose_name='Type')),
                ('source_subject', models.CharField(max_length=100, verbose_name='Source Subject')),
                ('collection_date', models.DateTimeField(blank=True, null=True, verbose_name='Collection Date')),
                ('volume', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Volume')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='Unit')),
                ('storage_location', models.CharField(blank=True, max_length=255, verbose_name='Storage Location')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('DEPLETED', 'Depleted'), ('RESERVED', 'Reserved'), ('DESTROYED', 'Destroyed')], default='AVAILABLE', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Specimen',
                'verbose_name_plural': 'Specimens',
                'ordering': ['-created_at'],
            },
        ),
    ]
