# Generated by Django 5.2.10 on 2026-01-15 16:28

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specimens', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSpecimen',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('specimen_id', models.CharField(db_index=True, max_length=100, verbose_name='Specimen ID')),
                ('collection_id', models.CharField(blank=True, max_length=100, verbose_name='Collection ID')),
                ('type', models.CharField(choices=[('BLOOD', 'Blood'), ('SERUM', 'Serum'), ('PLASMA', 'Plasma'), ('DNA', 'DNA'), ('RNA', 'RNA'), ('TISSUE', 'Tissue'), ('URINE', 'Urine'), ('OTHER', 'Other')], default='OTHER', max_length=20, verbose_name='Type')),
                ('source_subject', models.CharField(max_length=100, verbose_name='Source Subject')),
                ('collection_date', models.DateTimeField(blank=True, null=True, verbose_name='Collection Date')),
                ('volume', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Volume')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='Unit')),
                ('storage_location', models.CharField(blank=True, max_length=255, verbose_name='Storage Location')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('DEPLETED', 'Depleted'), ('RESERVED', 'Reserved'), ('DESTROYED', 'Destroyed')], default='AVAILABLE', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Specimen',
                'verbose_name_plural': 'historical Specimens',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
