# Generated by Django 5.2.10 on 2026-01-15 16:31

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specimens', '0002_historicalspecimen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('type', models.CharField(blank=True, max_length=50, verbose_name='Type')),
                ('rows', models.PositiveIntegerField(default=1, verbose_name='Rows')),
                ('cols', models.PositiveIntegerField(default=1, verbose_name='Columns')),
            ],
            options={
                'verbose_name': 'Container',
                'verbose_name_plural': 'Containers',
            },
        ),
        migrations.RemoveField(
            model_name='historicalspecimen',
            name='storage_location',
        ),
        migrations.RemoveField(
            model_name='specimen',
            name='storage_location',
        ),
        migrations.AddField(
            model_name='historicalspecimen',
            name='column',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Column'),
        ),
        migrations.AddField(
            model_name='historicalspecimen',
            name='row',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Row'),
        ),
        migrations.AddField(
            model_name='specimen',
            name='column',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Column'),
        ),
        migrations.AddField(
            model_name='specimen',
            name='row',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Row'),
        ),
        migrations.AddField(
            model_name='historicalspecimen',
            name='container',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='specimens.container', verbose_name='Container'),
        ),
        migrations.AddField(
            model_name='specimen',
            name='container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specimens', to='specimens.container', verbose_name='Container'),
        ),
        migrations.CreateModel(
            name='ContainerLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='specimens.containerlocation', verbose_name='Parent Location')),
            ],
            options={
                'verbose_name': 'Container Location',
                'verbose_name_plural': 'Container Locations',
            },
        ),
        migrations.AddField(
            model_name='container',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='containers', to='specimens.containerlocation', verbose_name='Location'),
        ),
        migrations.CreateModel(
            name='HistoricalContainer',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('type', models.CharField(blank=True, max_length=50, verbose_name='Type')),
                ('rows', models.PositiveIntegerField(default=1, verbose_name='Rows')),
                ('cols', models.PositiveIntegerField(default=1, verbose_name='Columns')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='specimens.containerlocation', verbose_name='Location')),
            ],
            options={
                'verbose_name': 'historical Container',
                'verbose_name_plural': 'historical Containers',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalContainerLocation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='specimens.containerlocation', verbose_name='Parent Location')),
            ],
            options={
                'verbose_name': 'historical Container Location',
                'verbose_name_plural': 'historical Container Locations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
