# Generated by Django 5.2.10 on 2026-01-15 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specimens', '0003_container_remove_historicalspecimen_storage_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalspecimen',
            name='parent_specimen',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='specimens.specimen', verbose_name='Parent Specimen'),
        ),
        migrations.AddField(
            model_name='specimen',
            name='parent_specimen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aliquots', to='specimens.specimen', verbose_name='Parent Specimen'),
        ),
    ]
