# Generated by Django 5.2.11 on 2026-02-09 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specimen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biospecimen',
            name='metadata',
            field=models.JSONField(blank=True, null=True, verbose_name='Metadata'),
        ),
        migrations.AddField(
            model_name='historicalbiospecimen',
            name='metadata',
            field=models.JSONField(blank=True, null=True, verbose_name='Metadata'),
        ),
    ]
